### ISSUE TITLE
Pretrained model doesn't appear to be compatible

### ISSUE THREAD

**Issue by n00mkrad** [kalpeshjp89/USISResNet#2]
When I try to run the test script, I get this:

```
RuntimeError: Error(s) in loading state_dict for RRDBNet:
        size mismatch for model.0.weight: copying a param with shape torch.Size([32, 3, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 3, 3, 3]).
```

This is what I set in the test json file:

` , "pretrain_model_G": "D:/AI/GAN/USISResNet/latest_G.pth"`

**Comment by kalpeshjp89** [comment]
I have provided pre-trained model which is 116000_G.pth. You are giving wrong network (latest_G.pth, which i have not shared) to load which shows you error.
Waiting for your reply.
 Thanking you.

**Comment by kalpeshjp89** [comment]
Now it is solved.
