### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for RRDBNet:

### ISSUE THREAD

**Issue by DanChen001** [kalpeshjp89/USISResNet#3]
Thank you for sharing the code.  I have the following problem. Could you give me some suggestions? Thanks.

****************************************************************************************************

RuntimeError: Error(s) in loading state_dict for RRDBNet:

        size mismatch for model.0.weight: copying a param with shape torch.Size([32, 3, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 3, 3, 3]).
        size mismatch for model.1.sub.0.RDB1.conv1.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.0.RDB1.conv2.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.0.RDB1.conv3.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.0.RDB1.conv4.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.0.RDB2.conv1.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.0.RDB2.conv2.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.0.RDB2.conv3.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.0.RDB2.conv4.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.0.RDB3.conv1.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.0.RDB3.conv2.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.0.RDB3.conv3.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.0.RDB3.conv4.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.1.RDB1.conv1.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.1.RDB1.conv2.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.1.RDB1.conv3.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.1.RDB1.conv4.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.1.RDB2.conv1.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.1.RDB2.conv2.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.1.RDB2.conv3.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.1.RDB2.conv4.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.1.RDB3.conv1.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.1.RDB3.conv2.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.1.RDB3.conv3.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.1.RDB3.conv4.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.2.RDB1.conv1.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.2.RDB1.conv2.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.2.RDB1.conv3.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.2.RDB1.conv4.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.2.RDB2.conv1.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.2.RDB2.conv2.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.2.RDB2.conv3.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.2.RDB2.conv4.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.2.RDB3.conv1.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.2.RDB3.conv2.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.2.RDB3.conv3.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.2.RDB3.conv4.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.3.RDB1.conv1.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.3.RDB1.conv2.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.3.RDB1.conv3.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.3.RDB1.conv4.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.3.RDB2.conv1.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.3.RDB2.conv2.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.3.RDB2.conv3.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.3.RDB2.conv4.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.3.RDB3.conv1.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.3.RDB3.conv2.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.3.RDB3.conv3.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.3.RDB3.conv4.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.4.RDB1.conv1.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.4.RDB1.conv2.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.4.RDB1.conv3.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.4.RDB1.conv4.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.4.RDB2.conv1.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.4.RDB2.conv2.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.4.RDB2.conv3.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.4.RDB2.conv4.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.4.RDB3.conv1.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.4.RDB3.conv2.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.4.RDB3.conv3.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.4.RDB3.conv4.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.5.RDB1.conv1.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.5.RDB1.conv2.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.5.RDB1.conv3.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.5.RDB1.conv4.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.5.RDB2.conv1.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.5.RDB2.conv2.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.5.RDB2.conv3.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.5.RDB2.conv4.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.5.RDB3.conv1.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.5.RDB3.conv2.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.5.RDB3.conv3.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.5.RDB3.conv4.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.6.RDB1.conv1.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.6.RDB1.conv2.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.6.RDB1.conv3.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.6.RDB1.conv4.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.6.RDB2.conv1.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.6.RDB2.conv2.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.6.RDB2.conv3.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.6.RDB2.conv4.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.6.RDB3.conv1.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.6.RDB3.conv2.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.6.RDB3.conv3.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.6.RDB3.conv4.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.7.RDB1.conv1.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.7.RDB1.conv2.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.7.RDB1.conv3.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.7.RDB1.conv4.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.7.RDB2.conv1.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.7.RDB2.conv2.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.7.RDB2.conv3.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.7.RDB2.conv4.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.7.RDB3.conv1.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.7.RDB3.conv2.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.7.RDB3.conv3.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.7.RDB3.conv4.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.8.RDB1.conv1.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.8.RDB1.conv2.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.8.RDB1.conv3.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.8.RDB1.conv4.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.8.RDB2.conv1.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.8.RDB2.conv2.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.8.RDB2.conv3.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.8.RDB2.conv4.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.8.RDB3.conv1.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.8.RDB3.conv2.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.8.RDB3.conv3.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.8.RDB3.conv4.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.9.RDB1.conv1.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.9.RDB1.conv2.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.9.RDB1.conv3.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.9.RDB1.conv4.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.9.RDB2.conv1.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.9.RDB2.conv2.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.9.RDB2.conv3.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.9.RDB2.conv4.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.9.RDB3.conv1.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.9.RDB3.conv2.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.9.RDB3.conv3.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.9.RDB3.conv4.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.10.RDB1.conv1.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.10.RDB1.conv2.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.10.RDB1.conv3.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.10.RDB1.conv4.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.10.RDB2.conv1.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.10.RDB2.conv2.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.10.RDB2.conv3.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.10.RDB2.conv4.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.10.RDB3.conv1.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.10.RDB3.conv2.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.10.RDB3.conv3.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.10.RDB3.conv4.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.11.RDB1.conv1.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.11.RDB1.conv2.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.11.RDB1.conv3.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.11.RDB1.conv4.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.11.RDB2.conv1.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.11.RDB2.conv2.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.11.RDB2.conv3.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.11.RDB2.conv4.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.11.RDB3.conv1.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.11.RDB3.conv2.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.11.RDB3.conv3.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.11.RDB3.conv4.0.weight: copying a param with shape torch.Size([32, 32, 5, 5]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
        size mismatch for model.1.sub.24.weight: copying a param with shape torch.Size([32, 32, 1, 1]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).

**Comment by kalpeshjp89** [comment]
Hello,
Sorry for the late reply.
By mistake, I was loading different model in the code which uploaded on
GitHub.
Now it is working. If you don't want to download it again, just change RRDB
to RRDB2 in line 87 (defination of define_G1) of network.py file.
Let me know if this works for you or not.
