### ISSUE TITLE
the pretrained model of the QA network 

### ISSUE THREAD

**Issue by Wenretium** [kalpeshjp89/USISResNet#4]
Hello, I want to ask something about the pretrained model of the QA network mentioned in the following line of code
load_path_Q = "/media/dl/DL/Kalpesh/Image Quality/experiments/VGGGAP_Kadid_Qualifier/models/latest_G.pth"
Can I train the same model as you with the codes provided? As I can't find the corresponding part of codes, could you please share the model? I only want to use the QA part of you whole model. Thanks.

**Comment by kalpeshjp89** [comment]
In this project, I haven't included the code for QA network training. But you can train it easily since the model is included in this project. Just need to set loader according to your data. Even if you want, I can share with you on mail.

**Comment by Wenretium** [comment]
I've solved this problem. As a beginner in deep learning, sorry to bother you and thank you all the same.

**Comment by kalpeshjp89** [comment]
Thank you.
